### ISSUE TITLE
error: expression must have a constant value

### ISSUE THREAD

**Issue by haoliuhl** [mayone/NCTU-CS-103-1-CG#1]
Hi, 

I tried to reproduce the desired result of the project, but it always shows an error message in lighting() function from line 176 to line 179, saying that `light_data`   expression must have a constant value. My running environment is VS2013 with glut correctly installed. Could you help me? Thanks.

**Comment by mayone** [comment]
Hello Erichliu00,
    Sorry that I haven't checked my github for a while. I think you are running the scene in 1-2 right? And can you run other program correctly, ex. Scenes in 1-1? Since all these programs use the same class for "light". Maybe you are using a compiler which doesn't support the syntax of c++11. If that's the case, you can use newer version of compiler or use "new" to build the dynamic 2d array.
Thanks for your report.
